# Generated by Django 3.0.2 on 2020-01-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakazy', '0003_auto_20200131_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
