# Generated by Django 3.0.2 on 2020-02-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0003_produkt_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produktimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
